<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-VU1F7B6" failures="1" tests="6" name="parallel_execution.Programme_Parallel1" time="14.583" errors="0" timestamp="2023-03-02T20:49:08 IST" skipped="0">
  <testcase classname="parallel_execution.Programme_Parallel1" name="login" time="2.041"/>
  <system-out/>
  <testcase classname="parallel_execution.Programme_Parallel1" name="login" time="2.707"/>
  <system-out/>
  <testcase classname="parallel_execution.Programme_Parallel1" name="login" time="2.338"/>
  <system-out/>
  <testcase classname="parallel_execution.Programme_Parallel1" name="title" time="3.619">
    <failure message="The following asserts failed:
	expected [actiTIME - Login] but found [actiTIME - Enter Time-Track]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [actiTIME - Login] but found [actiTIME - Enter Time-Track]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at parallel_execution.Programme_Parallel1.title(Programme_Parallel1.java:66)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- title -->
  <system-out/>
  <testcase classname="parallel_execution.Programme_Parallel1" name="title" time="0.020"/>
  <system-out/>
  <testcase classname="parallel_execution.Programme_Parallel1" name="title" time="3.858"/>
  <system-out/>
</testsuite> <!-- parallel_execution.Programme_Parallel1 -->
